[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
combinations = "0.1.0"

[[bin]]
name = "day7"
test = true
path = "src/day7.rs"

[[bin]]
name = "day8"
test = true
path = "src/day8.rs"

[[bin]]
name = "day9"
test = true
path = "src/day9.rs"
